#pragma once

#include <cstdint>
#include <array>
#include <chrono>

namespace busbridge::can {

/**
 * @brief Maximum CAN payload size in bytes
 * @details Standard CAN frames support up to 8 bytes of data
 */
constexpr size_t MAX_CAN_DATA_SIZE = 8;

/**
 * @struct CANMessage
 * @brief Represents a CAN message frame
 * 
 * @details
 * This structure encapsulates a complete CAN message with all relevant information.
 * Supports both standard (11-bit) and extended (29-bit) identifiers.
 * 
 * @note Thread-safe for reading; copy semantics for thread-safe passing between threads
 * 
 * @see https://en.wikipedia.org/wiki/CAN_bus
 */
struct CANMessage {
    /**
     * @brief CAN identifier (11-bit or 29-bit)
     * @details 
     * - For standard frames: bits [10:0] contain the ID
     * - For extended frames: all 29 bits contain the ID
     */
    uint32_t id;

    /**
     * @brief Data Length Code (0-8)
     * @details Specifies how many bytes of valid data are in the @c data array
     * @warning Must be <= MAX_CAN_DATA_SIZE
     */
    uint8_t dlc;

    /**
     * @brief CAN frame payload data
     * @details Only the first @c dlc bytes contain valid data
     */
    std::array<uint8_t, MAX_CAN_DATA_SIZE> data;

    /**
     * @brief Timestamp when message was received (microseconds since epoch)
     * @details 
     * Captured by the SocketCAN kernel interface. Useful for:
     * - Message ordering verification
     * - Bus load calculation
     * - Timing analysis
     */
    uint64_t timestamp;

    /**
     * @brief Flag indicating extended (29-bit) CAN identifier
     * @details 
     * - true: Extended frame (29-bit ID)
     * - false: Standard frame (11-bit ID)
     */
    bool is_extended;

    /**
     * @brief Flag indicating remote transmission request
     * @details Remote frames request data without payload
     */
    bool is_rtr;

    /**
     * @brief Flag indicating error frame
     * @details Error frames are generated by CAN controllers on protocol errors
     */
    bool is_error;

    /**
     * @brief Default constructor
     * @details Initializes all fields to zero/false
     */
    CANMessage() : id(0), dlc(0), data{}, timestamp(0), 
                   is_extended(false), is_rtr(false), is_error(false) {}

    /**
     * @brief Constructor with parameters
     * @param msg_id CAN identifier
     * @param msg_dlc Data length code (0-8)
     * @param msg_timestamp Reception timestamp
     * @param extended_id Whether identifier is extended (29-bit)
     */
    CANMessage(uint32_t msg_id, uint8_t msg_dlc, uint64_t msg_timestamp = 0, 
               bool extended_id = false)
        : id(msg_id), dlc(msg_dlc), timestamp(msg_timestamp), 
          is_extended(extended_id), is_rtr(false), is_error(false) {}

    /**
     * @brief Check if message contains valid data
     * @return true if dlc > 0 and not a remote/error frame
     */
    bool hasData() const { return dlc > 0 && !is_rtr && !is_error; }
};

}  // namespace busbridge::can
